server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Página /admin é um arquivo estático admin.html
    location = /admin {
        try_files /admin.html =404;
    }

    # Rotas principais (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Assets estáticos
    location /assets/ {
        alias /usr/share/nginx/html/assets/;
    }
}
